-----------------------------
---- DANK MATERIAL SHELL ----
-----------------------------

-- Integration with DMS (Quickshell-based shell). DMS regenerates the
-- files in ~/.config/hypr/dms/ itself (colors from the wallpaper, etc.),
-- so they are not part of the dotfiles and are loaded only if present.

local mainMod = "SUPER"

local function optional_require(name)
    local ok, err = pcall(require, name)

    -- Only a missing file is ignored; real errors still surface.
    if not ok and not tostring(err):find("module '" .. name .. "' not found", 1, true) then
        error(err)
    end
end

-- Border and group colors generated by DMS. Loaded after appearance.lua,
-- so they override its border colors.
optional_require("dms.colors")

-- DMS surfaces handle their own animations.
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

local function dms(command)
    return hl.dsp.exec_cmd("dms ipc call " .. command)
end

--------------------------------------------------
-- KEYBINDS
--------------------------------------------------

-- Only binds that do not collide with modules/keybinds.lua.

hl.bind(mainMod .. " + TAB", dms("hypr toggleOverview"))
hl.bind(mainMod .. " + O", dms("hypr toggleOverview"))

hl.bind(mainMod .. " + space", dms("spotlight toggle"))
hl.bind("ALT + space", dms("spotlight-bar toggle"))
hl.bind(mainMod .. " + comma", dms("settings focusOrToggle"))
hl.bind(mainMod .. " + N", dms("notifications toggle"))
hl.bind(mainMod .. " + SHIFT + N", dms("notepad toggle"))
hl.bind(mainMod .. " + Y", dms("dash toggle wallpaper"))
hl.bind(mainMod .. " + X", dms("powermenu toggle"))
hl.bind(mainMod .. " + SHIFT + Slash", dms("keybinds toggle hyprland"))

hl.bind(mainMod .. " + ALT + L", dms("lock lock"))
hl.bind("CTRL + ALT + Delete", dms("processlist focusOrToggle"))

hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))
