#!/usr/bin/env python3
"""Validate and atomically promote DMS Matugen's semantic color overlay."""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
BUILDER_PATH = ROOT / "scripts/build-theme.py"
SPEC = importlib.util.spec_from_file_location("build_theme", BUILDER_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"cannot load theme validator at {BUILDER_PATH}")
BUILD_THEME = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(BUILD_THEME)


def read_candidate(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read Matugen candidate: {exc}") from exc
    errors = BUILD_THEME.validate_dynamic_theme(value)
    if errors:
        raise ValueError("candidate failed semantic validation:\n- " + "\n- ".join(errors))
    return value


def render_hyprland_lua(theme: dict[str, Any]) -> str:
    """Render only validated semantic roles into a small Hyprland Lua module."""
    tokens = theme["tokens"]
    active = tokens["accents"]["primary"][1:]
    inactive = tokens["borders"]["default"][1:]
    error = tokens["semantic"]["error"][1:]
    return f'''-- Generated from validated DMS Matugen semantic colors.
-- Do not edit this file; Graphite Slate remains the static fallback.
hl.config({{
    general = {{
        col = {{
            active_border = "rgb({active})",
            inactive_border = "rgb({inactive})",
        }},
    }},
    group = {{
        col = {{
            border_active = "rgb({active})",
            border_inactive = "rgb({inactive})",
            border_locked_active = "rgb({error})",
            border_locked_inactive = "rgb({inactive})",
        }},
        groupbar = {{
            col = {{
                active = "rgb({active})",
                inactive = "rgb({inactive})",
                locked_active = "rgb({error})",
                locked_inactive = "rgb({inactive})",
            }},
        }},
    }},
}})
'''


def write_atomic(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_path, path)
        temporary_path = None
        directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def active_config_supports_bridge(config_dir: Path) -> bool:
    main_config = config_dir / "hyprland.lua"
    dms_module = config_dir / "modules/dms.lua"
    try:
        main_text = main_config.read_text(encoding="utf-8")
        dms_text = dms_module.read_text(encoding="utf-8")
    except OSError:
        return False
    loads_dms = re.search(r'require\s*\(\s*["\']modules\.dms["\']\s*\)', main_text)
    loads_bridge = re.search(r'optional_require\s*\(\s*["\']dms\.dotfiles_theme["\']\s*\)', dms_text)
    return bool(loads_dms and loads_bridge)


def hyprland_expression(theme: dict[str, Any]) -> str:
    lua_module = render_hyprland_lua(theme)
    return lua_module.removeprefix("-- Generated from validated DMS Matugen semantic colors.\n-- Do not edit this file; Graphite Slate remains the static fallback.\n")


def apply_live(theme: dict[str, Any], config_dir: Path) -> bool:
    if not os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        print("live Hyprland apply skipped: no active Hyprland instance", file=sys.stderr)
        return False
    if not active_config_supports_bridge(config_dir):
        print("live Hyprland apply skipped: active config does not load the semantic bridge", file=sys.stderr)
        return False
    expression = hyprland_expression(theme)
    try:
        result = subprocess.run(
            ["hyprctl", "eval", expression],
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"live Hyprland apply skipped: {exc}", file=sys.stderr)
        return False
    if result.returncode != 0 or result.stdout.strip() != "ok":
        detail = result.stderr.strip() or result.stdout.strip() or f"exit {result.returncode}"
        print(f"live Hyprland apply failed; generated module remains for next config load: {detail}", file=sys.stderr)
        return False
    print("applied validated dynamic colors to the active Hyprland instance")
    return True


def promote(candidate: Path, output: Path, runtime_lua: Path | None = None, live: bool = False,
            config_dir: Path | None = None) -> dict[str, Any]:
    if candidate.resolve() == output.resolve():
        raise ValueError("candidate and output must be different files")
    value = read_candidate(candidate)
    encoded = (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    generated_lua = render_hyprland_lua(value).encode("utf-8") if runtime_lua is not None else None
    previous_output = output.read_bytes() if output.exists() else None
    previous_lua = runtime_lua.read_bytes() if runtime_lua and runtime_lua.exists() else None
    try:
        write_atomic(output, encoded)
        if runtime_lua is not None and generated_lua is not None:
            write_atomic(runtime_lua, generated_lua)
    except OSError:
        # Roll back the pair if one atomic replacement fails.
        if previous_output is None:
            output.unlink(missing_ok=True)
        else:
            write_atomic(output, previous_output)
        if runtime_lua is not None:
            if previous_lua is None:
                runtime_lua.unlink(missing_ok=True)
            else:
                write_atomic(runtime_lua, previous_lua)
        raise
    candidate.unlink(missing_ok=True)
    if live:
        apply_live(value, config_dir or (Path.home() / ".config/hypr"))
    return value


def apply_existing(state: Path, runtime_lua: Path, live: bool = False,
                   config_dir: Path | None = None) -> bool:
    value = read_candidate(state)
    write_atomic(runtime_lua, render_hyprland_lua(value).encode("utf-8"))
    if live:
        return apply_live(value, config_dir or (Path.home() / ".config/hypr"))
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--candidate", type=Path)
    source.add_argument("--apply-existing", type=Path, metavar="STATE_JSON",
                        help="validate existing last-known-good JSON and regenerate the Lua consumer")
    parser.add_argument("--output", type=Path, help="last-known-good JSON destination (required with --candidate)")
    parser.add_argument("--runtime-lua", type=Path, required=True,
                        help="generated Hyprland Lua consumer path")
    parser.add_argument("--apply-live", action="store_true",
                        help="apply colors with hyprctl eval when the active config supports the bridge")
    parser.add_argument("--config-dir", type=Path, default=Path.home() / ".config/hypr",
                        help=argparse.SUPPRESS)
    args = parser.parse_args()

    try:
        if args.candidate:
            if not args.output:
                parser.error("--output is required with --candidate")
            promote(args.candidate, args.output, args.runtime_lua, args.apply_live, args.config_dir)
        else:
            apply_existing(args.apply_existing, args.runtime_lua, args.apply_live, args.config_dir)
    except (OSError, ValueError) as exc:
        print(f"dynamic theme was not promoted: {exc}", file=sys.stderr)
        return 1

    if args.candidate:
        print(f"promoted validated dynamic theme to {args.output} and generated {args.runtime_lua}")
    else:
        print(f"generated {args.runtime_lua} from validated state {args.apply_existing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
